### ISSUE TITLE
Add support for xdebug memory usage tracing (xdebug.show_mem_delta=1)

### ISSUE THREAD

**Issue by ottok** [alpha0010/webgrind#1]
It would be great if webgrind could handle xdebug's new trace format which includes memory usage.

Se more on:
http://derickrethans.nl/xdebug-and-tracing-memory-usage.html

(issue copied from https://code.google.com/p/webgrind/issues/detail?id=52 as it is still relevant)

**Comment by alpha0010** [comment]
Development has moved [upstream](https://github.com/jokkedk/webgrind).  This issue is being tracked [here](https://github.com/jokkedk/webgrind/issues/51).
