### ISSUE TITLE
Undefined offset: 2 in /alidata/webgrind/library/Preprocessor.php on line 209

### ISSUE THREAD

**Issue by fs523577192** [alpha0010/webgrind#2]
There are errors in the response of the index.php after clicking the [update] button:
    Notice: Undefined offset: 2 in /alidata/webgrind/library/Preprocessor.php on line 209
The code does not guarantee $matches[2] is set.

**Comment by alpha0010** [comment]
Thanks for the report.  Can you supply a cachegrind file that reproduces this?
