### ISSUE TITLE
Webgrind suddenly stopped working

### ISSUE THREAD

**Issue by svivian** [alpha0010/webgrind#3]
Hi, opening this ticket here since it seems like you're a bit more responsive :)

I'm having a strange issue with webgrind. When I first installed it (jokkedk's version) I had no problems. However today I tried profiling something new and webgrind no longer works (was jokkedk's version, but I've since installed your version and get the same results).

Xdebug takes creates the callgrind file OK. The webgrind "home page" loads fine and the dropdown menu has all the files in my output folder. But when I click "update" it doesn't load the file. The "Loading..." message pops up briefly but then just disappears with no indication of any error.

There are no JS errors in the Dev Tools console and no other errors displayed on the page. Older callgrind files that worked a few weeks ago do not load either. And the new callgrind file is perfectly valid because it loads in another tool (PHPStorm).

I thought maybe it was an issue with the `/tmp` directory but I've tried changing it with no luck. The `.webgrind` files are being written to the folder OK.

Any ideas? I can't think of anything else that could be causing the problem.

**Comment by alpha0010** [comment]
Do you have access to your apache logs?  Can you post a snippet from both the access and error logs for when you try to use webgrind?

**Comment by alpha0010** [comment]
No feedback, assuming resolved.  Please re-open if not.

**Comment by svivian** [comment]
Apologies, thought I'd already replied. The problem managed to fix itself! I'm not sure exactly what happened but I did remove some callgrind files from the folder so maybe one of those was breaking webgrind somehow.
