### ISSUE TITLE
Total Cost and Total Inclusive Cost shows 0 when percent is selected

### ISSUE THREAD

**Issue by fromcouch** [alpha0010/webgrind#7]
Hi, 

Total Cost and Total Inclusive Cost shows 0 when percent is selected. If I select milliseconds show values, but when percent is selected shows always 0.

![captura de pantalla 2016-05-10 a las 11 12 57](https://cloud.githubusercontent.com/assets/3542570/15141414/31ad664e-16a0-11e6-88de-6346801942f4.png)

No errors in log.

Thanks

**Comment by alpha0010** [comment]
Can you manually compute milliseconds/total_time?  If the percentage is less than 0.01% it will not be displayed.
I also see that (what I assume is) invocation count is very large.  Part of the computation relies on the size of PHP integers.  If your script runs long enough to overflow an integer, results are undefined.  (Webgrind is designed to handle web pages, and does not scale well up to large computation scripts.)  Could this be the case?

**Comment by alpha0010** [comment]
Not enough information to reproduce, closing.  If problem persists, please open a ticket [upstream](https://github.com/jokkedk/webgrind) (main repository is now active).
